### ISSUE TITLE
Problem with demo.js

### ISSUE THREAD

**Issue by ghost** [olalonde/mtgox-socket-client#3]
I get this error running demo.js:

```
gizurmaca00510e:mtgox-socket-client jonas$ node demo.js 
Opening socket.
connecting
websocket
Successfully connected
Got subscribe confirmation Trade
Got subscribe confirmation Ticker
Got subscribe confirmation Market Depth

/Users/jonas/git/colmsjo/mtgox-socket-client/console-formatting.js:6
  var time = '[' + datetime.format(now, '%T') + ']';
                   ^
ReferenceError: datetime is not defined
    at getTimeFormat (/Users/jonas/git/colmsjo/mtgox-socket-client/console-formatting.js:6:20)
    at renderDepthMessage (/Users/jonas/git/colmsjo/mtgox-socket-client/demo.js:73:15)
    at null.<anonymous> (/Users/jonas/git/colmsjo/mtgox-socket-client/demo.js:40:3)
    at EventEmitter.emit (events.js:88:17)
    at SocketNamespace.self.subscribePrivate.httpsClient.idKey.key (/Users/jonas/git/colmsjo/mtgox-socket-client/mtgox.js:75:11)
    at SocketNamespace.EventEmitter.emit [as $emit] (/Users/jonas/git/colmsjo/mtgox-socket-client/node_modules/socket.io-client/lib/events.js:167:15)
    at SocketNamespace.onPacket (/Users/jonas/git/colmsjo/mtgox-socket-client/node_modules/socket.io-client/lib/namespace.js:173:20)
    at Socket.onPacket (/Users/jonas/git/colmsjo/mtgox-socket-client/node_modules/socket.io-client/lib/socket.js:398:30)
    at Transport.onPacket (/Users/jonas/git/colmsjo/mtgox-socket-client/node_modules/socket.io-client/lib/transport.js:81:17)
    at Transport.onData (/Users/jonas/git/colmsjo/mtgox-socket-client/node_modules/socket.io-client/lib/transport.js:58:16)
```

**Comment by ghost** [comment]
It is simply this that is missing: `var datetime = require('datetime');`
